### ISSUE TITLE
Does not work on nodejs 8.9.1 or 9.2.0

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipld/js-ipld-cli#23]
Tried doing a build normally first. Got this error:

```
error ipld@0.6.0: The engine "node" is incompatible with this module. Expected version "^4.0.0".
```
From: https://ci.ipfs.team/blue/organizations/jenkins/IPLD%2Fjs-ipld-cli/detail/master/1/pipeline

Which, after running test run with ignoring the engines field, seems correct. Without checking engines, we get syntax errors when trying to run tests.

```
+ ./node_modules/.bin/yarn test

yarn run v1.3.2

$ aegir-test --env node

Usage of "module.dep" property is deprecated and will be removed in next major version. Use "deps" instead.

Usage of "module.dep" property is deprecated and will be removed in next major version. Use "deps" instead.

Usage of "module.dep" property is deprecated and will be removed in next major version. Use "deps" instead.

/tmp/jenkins/workspace/IPLD_js-ipld-cli_master-BNSJMLDZW3WKWLLLCVAFZGSKXEXFNKI3UB6X6OKEAMJ2VNR57VAQ/node_modules/gulp-git/node_modules/require-dir/index.js:93

            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/tmp/jenkins/workspace/IPLD_js-ipld-cli_master-BNSJMLDZW3WKWLLLCVAFZGSKXEXFNKI3UB6X6OKEAMJ2VNR57VAQ/node_modules/gulp-git/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/tmp/jenkins/workspace/IPLD_js-ipld-cli_master-BNSJMLDZW3WKWLLLCVAFZGSKXEXFNKI3UB6X6OKEAMJ2VNR57VAQ/node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/jenkins/workspace/IPLD_js-ipld-cli_master-BNSJMLDZW3WKWLLLCVAFZGSKXEXFNKI3UB6X6OKEAMJ2VNR57VAQ/node_modules/aegir/src/gulp-contributors.js:4:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
script returned exit code 1
```

From: https://ci.ipfs.team/blue/organizations/jenkins/IPLD%2Fjs-ipld-cli/detail/master/2/pipeline/20
